"""empty message

Revision ID: 1241cd01bb06
Revises: ac94170c532a
Create Date: 2022-08-13 00:33:05.213688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1241cd01bb06'
down_revision = 'ac94170c532a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'looking_for_venue')
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('venue', 'looking_for_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_talent')
    op.add_column('artist', sa.Column('looking_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
